### ISSUE TITLE
GPU Cuda 

### ISSUE THREAD

**Issue by TheDigitalCat** [tolokonov/A_Neural_Algorithm_of_Artistic_Style#1]
возможно ли перенести вычисления на видеокарту (нвидиа)?

**Comment by tolokonov** [comment]
Привет, @neznae4ko. В файле style_algorithm.py подгружается информация из окружения о доступных GPU 
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
Если вопрос касается непосредственно Streamlit, то вычисления на их стороне во много раз быстрее, чем у меня локально на CPU, поэтому, кажется, они неявно все же используют GPU, что, как по мне, аттракцион невиданной щедрости.
